Adds tests for when Redis service is unmanaged (#198)
* If the redis service is unmanaged, like so:
```
redis::managed_by_cluster_manager": true
redis::service_manage": false
redis::notify_service": false
```
then you get a compilation failure as it tries to
look for the redis service to notify:
```
But now an 'include ::redis' gives me:
Error: Could not find dependent Service[redis] for Augeas[Systemd redis ulimit] at /etc/puppet/modules/redis/manifests/ulimit.pp:44
```
* In fact, we don't need any service notification 
in the redis::ulimit class, as it's already in the
redis::config class, which notifies the service 
class anyways
* Adds spec for this use-case to avoid regression

Closes #197